-- Adjustable framing for player photos.
ALTER TABLE "Player"
  ADD COLUMN IF NOT EXISTS "photoZoom" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "photoPositionX" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "photoPositionY" INTEGER NOT NULL DEFAULT 50;
