ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "cookieBannerEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "privacyPolicyUrl" TEXT;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "cookiePolicyUrl" TEXT;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "adsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "adProvider" TEXT;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "adClientId" TEXT;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "adHomeSlot" TEXT;
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "adLeagueSlot" TEXT;
